### ISSUE TITLE
Reading ADS1256 registers

### ISSUE THREAD

**Issue by lucifer5298** [nradulovic/rtcomm-fw#1]
How to read individual registers from ads1256 IC . For Ex. Status registers and etc.

**Comment by lucifer5298** [comment]
I am experimenting with your ads1256.c driver code. Need to know how to access the ads1256.c driver code.

**Comment by nradulovic** [comment]
Hi, there is no function in ads1256.c that reads a value from a register. This module only configures the ADC to a specific acquisition mode and reads the acquisition data (which are outputted by the ADS1256). If you need to read data that was previously written then you would need to implement the function by yourself.

**Comment by lucifer5298** [comment]
Any guidance can you give, If I have to implement the logic to read individual registers for ads1256.c

**Comment by lucifer5298** [comment]
I tried but I am facing some problems.

**Comment by nradulovic** [comment]
I have no specific guidelines to give. Just follow the specification given in the datasheet regarding minimal timings for SPI communication and you should be good to go.
